### ISSUE TITLE
tools.map() also doesn't work

### ISSUE THREAD

**Issue by benjaminapetersen** [Asmodaios/tools.js#1]
Lodash and underscore.JS have examples if you need them.

**Comment by Asmodaios** [comment]
Is it just supposed to print the data?

**Comment by benjaminapetersen** [comment]
Nope!  Follow the API of http://underscorejs.org/#map or https://lodash.com/docs#map.  Map "Creates an array of values by running each element in collection through iteratee. "  The iteree is a function.

example:  

```javascript
// mapping an array to a 'times three' function
_.map([1, 2], function(item) {
   return item * 3;
});
// → [3, 6]

```

**Comment by benjaminapetersen** [comment]
Another example, using map to do nothing:

```javascript
map([1,2,3], function(item) {
   return item;
});
// → [1,2,3]
```

**Comment by benjaminapetersen** [comment]
Or, turn each item into an object:

```javascript
map([1,2,3], function(item) {
   return {
      num: item,
      str: String(item)
   }
});
// → [{num: 1, str: '1'},{num: 2, str: '2'},{num: 3, str: '3'}, ]
```

**Comment by benjaminapetersen** [comment]
map is a utility.  it doesn't "do" something to the items, it just ensures 1. a new array is created and 2. each item is transformed by the provided function one at a time.

**Comment by benjaminapetersen** [comment]
fixed? works?
