### ISSUE TITLE
Provide a minified version of code.

### ISSUE THREAD

**Issue by benjaminapetersen** [Asmodaios/tools.js#4]
Typically, source code is in the `/src` dir, and the final version is in the `/dist` dir.  
Do the following:
`cd /path/to/tools.js`
`mkdir src dist`
`npm init` and follow the instructions. yes to pretty much everything.
`npm install gulp gulp-util gulp-uglify gulp-rename gulp-concat del --save-dev`

This will give you a bunch of tools for minifying your project.

Then make a `gulpfile.js` in the root of your project, with the following:

```javascript
var gulp = require('gulp'),
  gutil = require('gulp-util'),
  uglify = require('gulp-uglify'),
  rename = require('gulp-rename'),
  concat = require('gulp-concat'),
  del = require('del');


gulp.task('default', function() {
   // do stuff here!
});
```

and do some googling to figure out how to minify your code & save the minified file as `/dist/tools.min.js`

**Comment by benjaminapetersen** [comment]
If that is confusing [here is an example](https://github.com/benjaminapetersen/angular-element-query).  the `/src` directory is all the source code, `/dist` is built for production use, and if you checkout the [gulpfile.js](https://github.com/benjaminapetersen/angular-element-query/blob/master/gulpfile.js), you can see what it does to do the minification.

**Comment by Asmodaios** [comment]
I essentially copied and pasted your code from your gulpfile.js to see how it would go, and tried running it via terminal and got a:

"Reference Error: rimraf is not defined."

When I tried using npm install gulp-rimraf, it said npm WARM rimraf deprecated or something.

**Comment by benjaminapetersen** [comment]
figure it out?  can't close it if its not done :smile:

**Comment by benjaminapetersen** [comment]
(ie, gotta read the file and fix the problem)
